version: '3'

services:
    nodejs:
        build:
          context: .
          dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        networks:
          - app-network

    webserver:
        image: nginx:latest
        container_name: webserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - web-root:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - dhparam:/etc/ssl/certs
        depends_on:
            - nodejs
        networks:
            - app-network
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - type: bind
                source: ./configs/htpasswd # we assume db.example.com file is in this folder on a host computer
                target: /etc/nginx/htpasswd
                read_only: true
            - type: bind
                source: /var/run/docker.sock
                target: /tmp/docker.sock
                read_only: true
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
          
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes: 
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on: 
            - webserver
        command: certonly --webroot --webroot-path=/var/www/html --email dhb220@gmail.com --agree-tos --no-eff-email --force-renewal -d docker.cmpartners.biz  -d www.docker.cmpartners.biz

volumes:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: /home/dhb220/tech_task/views/
            o: bind
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: /home/dhb220/tech_task/dhparam/
            o: bind
networks:
    app-network:
        driver: bridge




