version: '3'

services:
    nodejs:
        build:
          context: .
          dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        networks:
          - app-network

    webserver:
        image: nginx:latest
        container_name: webserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - web-root:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - dhparam:/etc/ssl/certs
        depends_on:
            - nodejs
        networks:
            - app-network
          
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes: 
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on: 
            - webserver
        command: certonly --webroot --webroot-path=/var/www/html --email dhb220@gmail.com --agree-tos --no-eff-email --force-renewal -d docker.cmpartners.biz  -d www.docker.cmpartners.biz

volumes:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: /home/dhb220/tech_task/views/
            o: bind
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: /home/dhb220/tech_task/dhparam/
            o: bind
networks:
    app-network:
        driver: bridge




